"""Self-contained HTML quotation/order-confirmation generator.

Ported from the original Tiger One desktop app's quote_document.py — same
layout and branding, so a customer or driver sees the same document whether
it came from the old desktop tool or this one.
"""
from __future__ import annotations

import base64
import html
import mimetypes
from datetime import datetime
from pathlib import Path

ORANGE = "#E3783E"
INK = "#17191C"


def esc(value, fallback=""):
    return html.escape(str(value if value not in (None, "") else fallback))


def cash(value):
    try:
        return f"£{float(value):,.2f}"
    except (TypeError, ValueError):
        return "£0.00"


def number(value):
    try:
        value = float(value)
        return f"{value:,.3f}".rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return "0"


def data_uri(path: str | Path) -> str:
    path = Path(path)
    mime = mimetypes.guess_type(str(path))[0] or "image/jpeg"
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode('ascii')}"


def uk_date(value) -> str:
    text = str(value or "").strip()
    for fmt in ("%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%d/%m/%Y"):
        try:
            parsed = datetime.strptime(text[:19], fmt)
            return f"{parsed.day} {parsed.strftime('%B %Y')}"
        except (ValueError, TypeError):
            pass
    return text


def item_table(items: list[dict], offset: int) -> str:
    rows = []
    for index, item in enumerate(items, start=offset + 1):
        rows.append(f"""<tr>
          <td class="centre">{index}</td>
          <td>{esc(item.get('description'))}</td>
          <td class="right">{number(item.get('quantity'))}</td>
          <td class="centre">{esc(item.get('unit'), 'm³')}</td>
          <td class="right">{cash(item.get('unit_price'))}</td>
          <td class="right"><b>{cash(item.get('line_total'))}</b></td>
        </tr>""")
    return f"""<table class="items">
      <thead><tr><th class="centre">Item</th><th>Description</th><th class="right">Quantity</th>
      <th class="centre">Unit</th><th class="right">Unit Price</th><th class="right">Line Total</th></tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>"""


def header(payload: dict, logo: str, page_number: int, page_count: int) -> str:
    label = esc(payload.get("document_label"), "QUOTATION")
    number_value = esc(payload.get("document_number") or payload.get("quote_number"))
    validity = "" if payload.get("document_label") == "ORDER CONFIRMATION" else f"<div><span>Valid for</span><b>{esc(payload.get('validity_days'), '14')} days</b></div>"
    return f"""<header>
      <div class="brand"><img src="{logo}" alt="Tiger Concrete Ltd"><div class="contact">
        Fresh concrete mixed on site<br>{esc(payload.get('company_address'))}<br>
        <b>{esc(payload.get('company_telephone'))}</b><br>{esc(payload.get('company_email'))}
      </div></div>
      <div class="document"><div class="doc-title">{label}</div>
        <div><span>Reference</span><b>{number_value}</b></div>
        <div><span>Revision</span><b>{esc(payload.get('revision'), 'A')}</b></div>
        <div><span>Date</span><b>{esc(uk_date(payload.get('created_at')))}</b></div>
        {validity}
        <div><span>Page</span><b>{page_number} of {page_count}</b></div>
      </div>
    </header>"""


def footer(payload: dict) -> str:
    label = esc(payload.get("document_label"), "QUOTATION")
    number_value = esc(payload.get("document_number") or payload.get("quote_number"))
    return f"""<footer><span>Tiger Concrete Ltd</span><b>Generated by Tiger One • Powered by ONE · Built by EIOP Software</b>
      <span class="right">{label} {number_value} • REV {esc(payload.get('revision'), 'A')}</span></footer>"""


def write_quote_html(path: str | Path, payload: dict, logo_path: str | Path) -> str:
    logo = data_uri(logo_path)
    all_items = list(payload.get("items") or [])
    page_capacity = 7
    chunks = [all_items[i:i + page_capacity] for i in range(0, len(all_items), page_capacity)] or [[]]
    page_count = len(chunks)
    pages = []
    offset = 0
    for page_number, chunk in enumerate(chunks, start=1):
        top = ""
        if page_number == 1:
            address = ", ".join(filter(None, [
                payload.get("address_1"), payload.get("address_2"), payload.get("town"), payload.get("postcode")
            ]))
            top = f"""<section class="details">
              <div class="box"><div class="box-title">Customer</div>
                <div class="field"><span>Type</span><b>{esc(payload.get('customer_type'))}</b></div>
                <div class="field"><span>Name</span><b>{esc(payload.get('customer_name'))}</b></div>
                <div class="field"><span>Contact</span><b>{esc(payload.get('contact_name'))}</b></div>
                <div class="field"><span>Telephone</span><b>{esc(payload.get('telephone') or payload.get('mobile'))}</b></div>
                <div class="field"><span>Address</span><b>{esc(address)}</b></div>
              </div>
              <div class="box"><div class="box-title">Pour requirements</div>
                <div class="field"><span>Project</span><b>{esc(payload.get('project'))}</b></div>
                <div class="field"><span>Site</span><b>{esc(payload.get('site_address'))}</b></div>
                <div class="field"><span>Requested</span><b>{esc(uk_date(payload.get('requested_date')))}</b></div>
                <div class="field"><span>Status</span><b>{esc(payload.get('status'))}</b></div>
                <div class="field"><span>Payment</span><b>{esc(payload.get('payment_terms'), 'To be agreed')}</b></div>
              </div>
            </section>"""
        bottom = ""
        if page_number == page_count:
            bottom = f"""<div class="totals">
              <div><span>Subtotal</span><b>{cash(payload.get('subtotal'))}</b></div>
              <div><span>VAT at {number(payload.get('tax_rate'))}%</span><b>{cash(payload.get('tax_total'))}</b></div>
              <div class="grand"><span>{'Order total' if payload.get('document_label') == 'ORDER CONFIRMATION' else 'Quotation total'}</span><b>{cash(payload.get('total'))}</b></div>
            </div>
            <section class="terms">
              <div><div class="box-title">Commercial terms</div>
                <p>Final concrete quantity is charged as delivered. The customer must provide safe and suitable site access, a suitable washout area and accurate dimensions. Cancellation, waiting-time and additional pumping charges may apply.</p>
              </div>
              <div><div class="box-title">Notes</div><p>{esc(payload.get('commercial_notes'), 'No additional notes.')}</p></div>
            </section>"""
        pages.append(f"""<article class="page{' continuation' if page_number > 1 else ''}">
          {header(payload, logo, page_number, page_count)}{top}
          <div class="project">{esc(payload.get('project'), 'Concrete supply quotation')}</div>
          {item_table(chunk, offset)}{bottom}{footer(payload)}
        </article>""")
        offset += len(chunk)

    document = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{esc(payload.get('document_label'), 'Quotation')} {esc(payload.get('document_number') or payload.get('quote_number'))}</title><style>
@page {{ size:A4 landscape; margin:8mm 10mm; }}
* {{ box-sizing:border-box; }}
html,body {{ margin:0; font-family:Arial,sans-serif; color:{INK}; font-size:8.2pt; }}
.page {{ position:relative; width:100%; height:194mm; min-height:194mm; overflow:hidden; display:flex; flex-direction:column; }}
.continuation {{ page-break-before:always; }}
header {{ display:flex; justify-content:space-between; align-items:flex-start; border-bottom:1.2mm solid {ORANGE}; padding-bottom:2.5mm; margin-bottom:3mm; }}
.brand {{ display:flex; align-items:center; gap:5mm; }} .brand img {{ width:76mm; max-height:17mm; object-fit:contain; object-position:left center; }}
.contact {{ border-left:.25mm solid #dfe2e4; padding-left:4mm; color:#454a51; font-size:7.5pt; line-height:1.45; }}
.document {{ min-width:70mm; color:white; background:{INK}; border-left:2mm solid {ORANGE}; padding:2.5mm 5mm; }}
.doc-title {{ font-size:15pt; font-weight:800; letter-spacing:.7mm; margin-bottom:1mm; }}
.document div:not(.doc-title) {{ display:flex; justify-content:space-between; gap:5mm; font-size:7.5pt; margin-top:.6mm; }}
.details,.terms {{ display:grid; grid-template-columns:1fr 1fr; gap:12mm; margin-bottom:3mm; }}
.box,.terms>div {{ border:.25mm solid #dfe2e4; border-top:.8mm solid {ORANGE}; }}
.box-title {{ background:#f4f5f5; padding:1.5mm 2.5mm; text-transform:uppercase; font-weight:800; font-size:7.5pt; letter-spacing:.2mm; }}
.field {{ display:grid; grid-template-columns:31mm 1fr; padding:1.1mm 2.5mm; border-top:.2mm solid #edf0f1; min-height:5.5mm; }}
.field span {{ color:#70757c; font-weight:700; }}
.project {{ font-weight:800; font-size:9pt; margin:1mm 0 2mm; }}
.items {{ width:100%; border-collapse:collapse; }} .items th {{ background:{INK}; color:white; padding:1.8mm 2.5mm; text-align:left; text-transform:uppercase; font-size:7.5pt; }}
.items td {{ padding:2mm 2.5mm; border-bottom:.22mm solid #dfe2e4; }} .items tbody tr:nth-child(even) {{ background:#f7f8f8; }}
.centre {{ text-align:center!important; }} .right {{ text-align:right!important; }}
.totals {{ margin:2.5mm 0 2mm auto; width:75mm; }} .totals div {{ display:grid; grid-template-columns:1fr 31mm; }}
.totals span,.totals b {{ padding:1.5mm 3mm; text-align:right; border-bottom:.2mm solid #dfe2e4; }}
.totals .grand span {{ color:white; background:{ORANGE}; text-transform:uppercase; font-weight:800; text-align:left; }}
.totals .grand b {{ border:.5mm solid {ORANGE}; font-size:9pt; }}
.terms {{ margin-top:1mm; gap:8mm; }} .terms p {{ padding:2mm 2.5mm; margin:0; line-height:1.45; }}
footer {{ position:absolute; bottom:0; left:0; right:0; border-top:.25mm solid #dfe2e4; padding-top:1.8mm; display:grid; grid-template-columns:1fr 1fr 1fr; color:#70757c; font-size:6.5pt; }}
footer b {{ text-align:center; color:{INK}; }} footer .right {{ text-align:right; }}
@media print {{ * {{ print-color-adjust:exact; -webkit-print-color-adjust:exact; }} }}
</style></head><body>{''.join(pages)}</body></html>"""
    output = Path(path).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8")
    return str(output)


def write_order_html(path: str | Path, payload: dict, logo_path: str | Path) -> str:
    prepared = dict(payload)
    prepared["document_label"] = "ORDER CONFIRMATION"
    prepared["document_number"] = prepared.get("order_number")
    return write_quote_html(path, prepared, logo_path)
